#ifndef __COMPONENTENUM_H
#define __COMPONENTENUM_H
/*
enum {
 IUSMALLCOMPONENT        ,//0
 USTBIGCOMPONENT         ,//1
 ACMDSMALLCOMPONENT      ,//2
 DOUTBIGCOMPONENT        ,//8
 DOUTSMALLCOMPONENT      ,//1
 DTRBIGCOMPONENT         ,//10
 ANDBIGCOMPONENT         ,//15
 UPRBIGCOMPONENT         ,//19
 DVBIGCOMPONENT          ,//9
 DVSMALLCOMPONENT        ,//6
 GCMDSMALLCOMPONENT      ,//3
 KEYBIGCOMPONENT         ,//13
 MFTBIGCOMPONENT         ,//12
 NOTBIGCOMPONENT         ,//17
 ORBIGCOMPONENT          ,//16
 PKVBIGCOMPONENT         ,//22
 RAISMALLCOMPONENT       ,//5
 PREGBIGCOMPONENT        ,//25
 REGBIGCOMPONENT         ,//25
 RPRBIGCOMPONENT         ,//21
 RPRSMALLCOMPONENT       ,//23
 SDIBIGCOMPONENT         ,//11
 SDISMALLCOMPONENT       ,//7
 VVBIGCOMPONENT          ,//14
 XORBIGCOMPONENT         ,//18
 YUSTBIGCOMPONENT        ,//24
 AISMALLCOMPONENT        ,//4
 QAISMALLCOMPONENT       ,//4
 PFBIGCOMPONENT          ,//4
 DFRESBIGCOMPONENT       ,//26
#if (((MODYFIKACIA_VERSII_PZ / 10) & 0x1) != 0)
 GOOSBIGCOMPONENT        ,//4
 MMSBIGCOMPONENT         ,//4
 LANBIGCOMPONENT         ,//4
#endif
#ifdef  MODYFIKACIA_VERSII_DS
 DOUTBIGDSCOMPONENT      ,//8
#endif
 TOTAL_COMPONENT         ,//26

 MARKER_OUTPERIMETR   = 100000,
 MARKER_ERRORPERIMETR = 100001,
 MARKER_ERRORDIAPAZON = 100002,
 MARKER_ERRORPAROL    = 100003
};

//макс размер буфера записи
#define MAXIMUMTW 128
//ошибка валидации
#define ERROR_VALID2 2
#define ERROR_VALID3 3
*/
#endif
