#ifndef __CONST_MENU_STATE_INPUTS_OUTPUTS__
#define __CONST_MENU_STATE_INPUTS_OUTPUTS__

#define EKRAN_LIST_INPUTS_OUTPUTS       (EKRAN_CONTROL_VMP + 1)
#define EKRAN_STATE_INPUTS              (EKRAN_LIST_INPUTS_OUTPUTS + 1)
#define EKRAN_STATE_OUTPUTS             (EKRAN_STATE_INPUTS + 1)

#define MAX_ROW_FOR_LIST_INPUTS_OUTPUTS  2

#define INDEX_ML_STATE_INPUTS                0
#define INDEX_ML_STATE_OUTPUTS               1

#endif
