#ifndef __CONSTANTS_DEFINED_NOT__
#define __CONSTANTS_DEFINED_NOT__

#define EKRAN_LIST_D_NOT                    (EKRAN_RANGUVANNJA_D_XOR8 + 1)
#define EKRAN_RANGUVANNJA_D_NOT1            (EKRAN_LIST_D_NOT + 1)
#define EKRAN_RANGUVANNJA_D_NOT2            (EKRAN_RANGUVANNJA_D_NOT1  + 1)
#define EKRAN_RANGUVANNJA_D_NOT3            (EKRAN_RANGUVANNJA_D_NOT2  + 1)
#define EKRAN_RANGUVANNJA_D_NOT4            (EKRAN_RANGUVANNJA_D_NOT3  + 1)
#define EKRAN_RANGUVANNJA_D_NOT5            (EKRAN_RANGUVANNJA_D_NOT4  + 1)
#define EKRAN_RANGUVANNJA_D_NOT6            (EKRAN_RANGUVANNJA_D_NOT5  + 1)
#define EKRAN_RANGUVANNJA_D_NOT7            (EKRAN_RANGUVANNJA_D_NOT6  + 1)
#define EKRAN_RANGUVANNJA_D_NOT8            (EKRAN_RANGUVANNJA_D_NOT7  + 1)
#define EKRAN_RANGUVANNJA_D_NOT9            (EKRAN_RANGUVANNJA_D_NOT8  + 1)
#define EKRAN_RANGUVANNJA_D_NOT10           (EKRAN_RANGUVANNJA_D_NOT9  + 1)
#define EKRAN_RANGUVANNJA_D_NOT11           (EKRAN_RANGUVANNJA_D_NOT10 + 1)
#define EKRAN_RANGUVANNJA_D_NOT12           (EKRAN_RANGUVANNJA_D_NOT11 + 1)
#define EKRAN_RANGUVANNJA_D_NOT13           (EKRAN_RANGUVANNJA_D_NOT12 + 1)
#define EKRAN_RANGUVANNJA_D_NOT14           (EKRAN_RANGUVANNJA_D_NOT13 + 1)
#define EKRAN_RANGUVANNJA_D_NOT15           (EKRAN_RANGUVANNJA_D_NOT14 + 1)
#define EKRAN_RANGUVANNJA_D_NOT16           (EKRAN_RANGUVANNJA_D_NOT15 + 1)

#define MAX_ROW_FOR_LIST_D_NOT              NUMBER_DEFINED_NOT/*((int)current_settings.number_defined_not)*/
#define MAX_ROW_RANGUVANNJA_D_NOT           NUMBER_TOTAL_SIGNAL_FOR_RANG

#endif 
