#ifndef __CONSTANTS_DEFINED_OR__
#define __CONSTANTS_DEFINED_OR__

#define EKRAN_LIST_D_OR                    (EKRAN_RANGUVANNJA_D_AND8 + 1)
#define EKRAN_RANGUVANNJA_D_OR1            (EKRAN_LIST_D_OR + 1)
#define EKRAN_RANGUVANNJA_D_OR2            (EKRAN_RANGUVANNJA_D_OR1 + 1)
#define EKRAN_RANGUVANNJA_D_OR3            (EKRAN_RANGUVANNJA_D_OR2 + 1)
#define EKRAN_RANGUVANNJA_D_OR4            (EKRAN_RANGUVANNJA_D_OR3 + 1)
#define EKRAN_RANGUVANNJA_D_OR5            (EKRAN_RANGUVANNJA_D_OR4 + 1)
#define EKRAN_RANGUVANNJA_D_OR6            (EKRAN_RANGUVANNJA_D_OR5 + 1)
#define EKRAN_RANGUVANNJA_D_OR7            (EKRAN_RANGUVANNJA_D_OR6 + 1)
#define EKRAN_RANGUVANNJA_D_OR8            (EKRAN_RANGUVANNJA_D_OR7 + 1)

#define MAX_ROW_FOR_LIST_D_OR              NUMBER_DEFINED_OR/*((int)current_settings.number_defined_or)*/
#define MAX_ROW_RANGUVANNJA_D_OR           NUMBER_TOTAL_SIGNAL_FOR_RANG

#endif 
