#ifndef __CONSTANTS_DEFINED_XOR__
#define __CONSTANTS_DEFINED_XOR__

#define EKRAN_LIST_D_XOR                    (EKRAN_RANGUVANNJA_D_OR8 + 1)
#define EKRAN_RANGUVANNJA_D_XOR1            (EKRAN_LIST_D_XOR + 1)
#define EKRAN_RANGUVANNJA_D_XOR2            (EKRAN_RANGUVANNJA_D_XOR1 + 1)
#define EKRAN_RANGUVANNJA_D_XOR3            (EKRAN_RANGUVANNJA_D_XOR2 + 1)
#define EKRAN_RANGUVANNJA_D_XOR4            (EKRAN_RANGUVANNJA_D_XOR3 + 1)
#define EKRAN_RANGUVANNJA_D_XOR5            (EKRAN_RANGUVANNJA_D_XOR4 + 1)
#define EKRAN_RANGUVANNJA_D_XOR6            (EKRAN_RANGUVANNJA_D_XOR5 + 1)
#define EKRAN_RANGUVANNJA_D_XOR7            (EKRAN_RANGUVANNJA_D_XOR6 + 1)
#define EKRAN_RANGUVANNJA_D_XOR8            (EKRAN_RANGUVANNJA_D_XOR7 + 1)

#define MAX_ROW_FOR_LIST_D_XOR              NUMBER_DEFINED_XOR/*((int)current_settings.number_defined_xor)*/
#define MAX_ROW_RANGUVANNJA_D_XOR           NUMBER_TOTAL_SIGNAL_FOR_RANG

#endif 
