#ifndef __CONST_MENU_CHOSE_EXTRA_SETTINGS__
#define __CONST_MENU_CHOSE_EXTRA_SETTINGS__

#define EKRAN_CHOSE_EXTRA_SETTINGS        (EKRAN_LEVEL_SET_NEW_PASSWORD3 + 1)

enum _index_ml_ctrextra
{
  INDEX_ML_CTREXTRA_SETTINGS_1_CTRL_READY_TU  = 0,
  INDEX_ML_CTREXTRA_SETTINGS_1_CTRL_WINDOW_OFF_CB,
  INDEX_ML_CTREXTRA_SETTINGS_1_CTRL_FB_ACTIVATION,
  
  MAX_ROW_FOR_CHOSE_EXTRA_SETTINGS
};

#define CTR_EXTRA_SETTINGS_1_MASKA  (MASKA_FOR_BIT(MAX_ROW_FOR_CHOSE_EXTRA_SETTINGS) - 1)

#endif
