#ifndef __CONSTANTS_LEDS__
#define __CONSTANTS_LEDS__

#define EKRAN_LIST_LEDS_FOR_RANGUVANNJA        (EKRAN_LIST_OUTPUTS_FOR_RANGUVANNJA + 1)

#define EKRAN_RANGUVANNJA_LED_1                (EKRAN_RANGUVANNJA_OUTPUT_LAST + 1)
#define EKRAN_RANGUVANNJA_LED_2                (EKRAN_RANGUVANNJA_LED_1 + 1)
#define EKRAN_RANGUVANNJA_LED_3                (EKRAN_RANGUVANNJA_LED_2 + 1)
#define EKRAN_RANGUVANNJA_LED_4                (EKRAN_RANGUVANNJA_LED_3 + 1)
#define EKRAN_RANGUVANNJA_LED_5                (EKRAN_RANGUVANNJA_LED_4 + 1)
#define EKRAN_RANGUVANNJA_LED_6                (EKRAN_RANGUVANNJA_LED_5 + 1)
#define EKRAN_RANGUVANNJA_LED_7                (EKRAN_RANGUVANNJA_LED_6 + 1)
#define EKRAN_RANGUVANNJA_LED_8                (EKRAN_RANGUVANNJA_LED_7 + 1)
#define EKRAN_RANGUVANNJA_LED_9                (EKRAN_RANGUVANNJA_LED_8 + 1)
#define EKRAN_RANGUVANNJA_LED_10               (EKRAN_RANGUVANNJA_LED_9 + 1)
#define EKRAN_RANGUVANNJA_LED_11               (EKRAN_RANGUVANNJA_LED_10 + 1)
#define EKRAN_RANGUVANNJA_LED_12               (EKRAN_RANGUVANNJA_LED_11 + 1)
#define EKRAN_RANGUVANNJA_LED_13               (EKRAN_RANGUVANNJA_LED_12 + 1)
#define EKRAN_RANGUVANNJA_LED_14               (EKRAN_RANGUVANNJA_LED_13 + 1)
#define EKRAN_RANGUVANNJA_LED_15               (EKRAN_RANGUVANNJA_LED_14 + 1)
#define EKRAN_RANGUVANNJA_LED_16               (EKRAN_RANGUVANNJA_LED_15 + 1)
#define EKRAN_RANGUVANNJA_LED_17               (EKRAN_RANGUVANNJA_LED_16 + 1)


#define MAX_ROW_LIST_LEDS_FOR_RANGUVANNJA       NUMBER_LEDS
#define MAX_ROW_RANGUVANNJA_LED                 NUMBER_TOTAL_SIGNAL_FOR_RANG

#endif 
