#ifndef __CONST_MENU_ZOP__
#define __CONST_MENU_ZOP__

#define EKRAN_SETPOINT_ZOP_GROUP1 (EKRAN_SETPOINT_UROV_GROUP4 + 1)
#define EKRAN_SETPOINT_ZOP_GROUP2 (EKRAN_SETPOINT_ZOP_GROUP1 + 1)
#define EKRAN_SETPOINT_ZOP_GROUP3 (EKRAN_SETPOINT_ZOP_GROUP2 + 1)
#define EKRAN_SETPOINT_ZOP_GROUP4 (EKRAN_SETPOINT_ZOP_GROUP3 + 1)
#define EKRAN_TIMEOUT_ZOP_GROUP1  (EKRAN_TIMEOUT_UROV_GROUP4  + 1)
#define EKRAN_TIMEOUT_ZOP_GROUP2  (EKRAN_TIMEOUT_ZOP_GROUP1  + 1)
#define EKRAN_TIMEOUT_ZOP_GROUP3  (EKRAN_TIMEOUT_ZOP_GROUP2  + 1)
#define EKRAN_TIMEOUT_ZOP_GROUP4  (EKRAN_TIMEOUT_ZOP_GROUP3  + 1)
#define EKRAN_CONTROL_ZOP         (EKRAN_CONTROL_UROV  + 1)

#define MAX_ROW_FOR_SETPOINT_ZOP  1
#define MAX_ROW_FOR_TIMEOUT_ZOP   1
#define MAX_ROW_FOR_CONTROL_ZOP   1

#define COL_SETPOINT_ZOP_BEGIN    4
#define COL_SETPOINT_ZOP_COMMA    5
#define COL_SETPOINT_ZOP_END      8

#define COL_TMO_ZOP_BEGIN         4
#define COL_TMO_ZOP_COMMA         6
#define COL_TMO_ZOP_END           8

#define CTR_ZOP_STATE_BIT         0          
#define CTR_ZOP_STATE             (1 << CTR_ZOP_STATE_BIT)          
#define CTR_ZOP_MASKA             (CTR_ZOP_STATE)

#endif
