#ifndef __CONSTANTS_DEFINED_FUNCTIONS__
#define __CONSTANTS_DEFINED_FUNCTIONS__

#define EKRAN_LIST_SETTINGS_FOR_DF              (EKRAN_GENERAL_PICKUPS_EL + 1)
#define EKRAN_LIST_TYPE_DF                      (EKRAN_LIST_SETTINGS_FOR_DF + 1)
#define EKRAN_LIST_DF_FOR_RANGUVANNJA           (EKRAN_LIST_TYPE_DF + 1)
#define EKRAN_LIST_DF_FOR_TIMEOUT_SETTINGS      (EKRAN_LIST_DF_FOR_RANGUVANNJA + 1)
#define EKRAN_TIMEOUT_DF1                       (EKRAN_LIST_DF_FOR_TIMEOUT_SETTINGS + 1)
#define EKRAN_TIMEOUT_DF2                       (EKRAN_TIMEOUT_DF1 + 1)
#define EKRAN_TIMEOUT_DF3                       (EKRAN_TIMEOUT_DF2 + 1)
#define EKRAN_TIMEOUT_DF4                       (EKRAN_TIMEOUT_DF3 + 1)
#define EKRAN_TIMEOUT_DF5                       (EKRAN_TIMEOUT_DF4 + 1)
#define EKRAN_TIMEOUT_DF6                       (EKRAN_TIMEOUT_DF5 + 1)
#define EKRAN_TIMEOUT_DF7                       (EKRAN_TIMEOUT_DF6 + 1)
#define EKRAN_TIMEOUT_DF8                       (EKRAN_TIMEOUT_DF7 + 1)
#define EKRAN_LIST_TYPE_SOURCE_DF1              (EKRAN_TIMEOUT_DF8 + 1)
#define EKRAN_LIST_TYPE_SOURCE_DF2              (EKRAN_LIST_TYPE_SOURCE_DF1 + 1)
#define EKRAN_LIST_TYPE_SOURCE_DF3              (EKRAN_LIST_TYPE_SOURCE_DF2 + 1)
#define EKRAN_LIST_TYPE_SOURCE_DF4              (EKRAN_LIST_TYPE_SOURCE_DF3 + 1)
#define EKRAN_LIST_TYPE_SOURCE_DF5              (EKRAN_LIST_TYPE_SOURCE_DF4 + 1)
#define EKRAN_LIST_TYPE_SOURCE_DF6              (EKRAN_LIST_TYPE_SOURCE_DF5 + 1)
#define EKRAN_LIST_TYPE_SOURCE_DF7              (EKRAN_LIST_TYPE_SOURCE_DF6 + 1)
#define EKRAN_LIST_TYPE_SOURCE_DF8              (EKRAN_LIST_TYPE_SOURCE_DF7 + 1)
#define EKRAN_RANGUVANNJA_DF1_PLUS              (EKRAN_LIST_TYPE_SOURCE_DF8 + 1)
#define EKRAN_RANGUVANNJA_DF1_MINUS             (EKRAN_RANGUVANNJA_DF1_PLUS + 1)
#define EKRAN_RANGUVANNJA_DF1_BLK               (EKRAN_RANGUVANNJA_DF1_MINUS + 1)
#define EKRAN_RANGUVANNJA_DF1_RESET             (EKRAN_RANGUVANNJA_DF1_BLK + 1)
#define EKRAN_RANGUVANNJA_DF2_PLUS              (EKRAN_RANGUVANNJA_DF1_RESET + 1)
#define EKRAN_RANGUVANNJA_DF2_MINUS             (EKRAN_RANGUVANNJA_DF2_PLUS + 1)
#define EKRAN_RANGUVANNJA_DF2_BLK               (EKRAN_RANGUVANNJA_DF2_MINUS + 1)
#define EKRAN_RANGUVANNJA_DF2_RESET             (EKRAN_RANGUVANNJA_DF2_BLK + 1)
#define EKRAN_RANGUVANNJA_DF3_PLUS              (EKRAN_RANGUVANNJA_DF2_RESET + 1)
#define EKRAN_RANGUVANNJA_DF3_MINUS             (EKRAN_RANGUVANNJA_DF3_PLUS + 1)
#define EKRAN_RANGUVANNJA_DF3_BLK               (EKRAN_RANGUVANNJA_DF3_MINUS + 1)
#define EKRAN_RANGUVANNJA_DF3_RESET             (EKRAN_RANGUVANNJA_DF3_BLK + 1)
#define EKRAN_RANGUVANNJA_DF4_PLUS              (EKRAN_RANGUVANNJA_DF3_RESET + 1)
#define EKRAN_RANGUVANNJA_DF4_MINUS             (EKRAN_RANGUVANNJA_DF4_PLUS + 1)
#define EKRAN_RANGUVANNJA_DF4_BLK               (EKRAN_RANGUVANNJA_DF4_MINUS + 1)
#define EKRAN_RANGUVANNJA_DF4_RESET             (EKRAN_RANGUVANNJA_DF4_BLK + 1)
#define EKRAN_RANGUVANNJA_DF5_PLUS              (EKRAN_RANGUVANNJA_DF4_RESET + 1)
#define EKRAN_RANGUVANNJA_DF5_MINUS             (EKRAN_RANGUVANNJA_DF5_PLUS + 1)
#define EKRAN_RANGUVANNJA_DF5_BLK               (EKRAN_RANGUVANNJA_DF5_MINUS + 1)
#define EKRAN_RANGUVANNJA_DF5_RESET             (EKRAN_RANGUVANNJA_DF5_BLK + 1)
#define EKRAN_RANGUVANNJA_DF6_PLUS              (EKRAN_RANGUVANNJA_DF5_RESET + 1)
#define EKRAN_RANGUVANNJA_DF6_MINUS             (EKRAN_RANGUVANNJA_DF6_PLUS + 1)
#define EKRAN_RANGUVANNJA_DF6_BLK               (EKRAN_RANGUVANNJA_DF6_MINUS + 1)
#define EKRAN_RANGUVANNJA_DF6_RESET             (EKRAN_RANGUVANNJA_DF6_BLK + 1)
#define EKRAN_RANGUVANNJA_DF7_PLUS              (EKRAN_RANGUVANNJA_DF6_RESET + 1)
#define EKRAN_RANGUVANNJA_DF7_MINUS             (EKRAN_RANGUVANNJA_DF7_PLUS + 1)
#define EKRAN_RANGUVANNJA_DF7_BLK               (EKRAN_RANGUVANNJA_DF7_MINUS + 1)
#define EKRAN_RANGUVANNJA_DF7_RESET             (EKRAN_RANGUVANNJA_DF7_BLK + 1)
#define EKRAN_RANGUVANNJA_DF8_PLUS              (EKRAN_RANGUVANNJA_DF7_RESET + 1)
#define EKRAN_RANGUVANNJA_DF8_MINUS             (EKRAN_RANGUVANNJA_DF8_PLUS + 1)
#define EKRAN_RANGUVANNJA_DF8_BLK               (EKRAN_RANGUVANNJA_DF8_MINUS + 1)
#define EKRAN_RANGUVANNJA_DF8_RESET             (EKRAN_RANGUVANNJA_DF8_BLK + 1)

#define MAX_ROW_SETTINGS_DF                      3
#define MAX_ROW_FOR_TYPE_DF                      NUMBER_DEFINED_FUNCTIONS/*((int)current_settings.number_defined_df)*/
#define MAX_ROW_FOR_LIST_DF                      NUMBER_DEFINED_FUNCTIONS/*((int)current_settings.number_defined_df)*/
#define MAX_ROW_TIMEOUT_DF                       2
#define MAX_ROW_RANGUVANNJA_DF                   NUMBER_TOTAL_SIGNAL_FOR_RANG


#define INDEX_ML_SETTING_DF_SOURCE            0
#define INDEX_ML_SETTING_DF_TIMEOUT           1
#define INDEX_ML_SETTING_DF_TYPE              2

#define INDEX_ML_TMO_DF_PAUSE                 0
#define INDEX_ML_TMO_DF_WORK                  1

enum
{
	INDEX_ML_LIST_TYPE_SOURCE_PLUS_DF = 0,
	INDEX_ML_LIST_TYPE_SOURCE_MINUS_DF,
	INDEX_ML_LIST_TYPE_SOURCE_BLK_DF,
	INDEX_ML_LIST_TYPE_SOURCE_R_DF,
	
	MAX_ROW_LIST_TYPE_SOURCE_DF
};

#define COL_TMO_DF_PAUSE_BEGIN                3
#define COL_TMO_DF_PAUSE_COMMA                6
#define COL_TMO_DF_PAUSE_END                  8

#define COL_TMO_DF_WORK_BEGIN                 3
#define COL_TMO_DF_WORK_COMMA                 6
#define COL_TMO_DF_WORK_END                   8

#endif 
