#ifndef __CONST_MENU_CONFIGURATION__
#define __CONST_MENU_CONFIGURATION__

#define EKRAN_COFIGURATION               (EKRAN_TIME + 1)

#define MAX_ROW_FOR_EKRAN_CONFIGURATION  TOTAL_NUMBER_PROTECTION

#endif
