#ifndef __CONST_MENU_POINT_TIME_SETTINGS__
#define __CONST_MENU_POINT_TIME_SETTINGS__

#define EKRAN_POINT_TIME_SETTINGS            (EKRAN_REPROGRAM + 1)
#define EKRAN_POINT_TIME_SETPOINT            (EKRAN_POINT_TIME_SETTINGS + 1)
#define EKRAN_POINT_TIME_RANGUVANNJA         (EKRAN_POINT_TIME_SETPOINT + 1)

#define MAX_ROW_FOR_POINT_TIME_SETTINGS      2  
#define MAX_ROW_FOR_POINT_TIME_SETPOINT_RANGUVANNJA      1 

#define INDEX_ML_TIME_SETPOINT               0
#define INDEX_ML_TIME_RANGUVANNJA            1

#endif
