#ifndef __CONST_MENU_GENERAL_PICKUPS_EL__
#define __CONST_MENU_GENERAL_PICKUPS_EL__

#define EKRAN_GENERAL_PICKUPS_EL            (EKRAN_EXTENDED_LIGIC + 1)

#define MAX_ROW_FOR_GENERAL_PICKUPS_EL      1/*7*/

#define INDEX_ML_NUMBER_INERATION           0
//#define INDEX_ML_NUMBER_DEFINED_FUNCTIONS   1
//#define INDEX_ML_NUMBER_DEFINED_TRIGGERS    2
//#define INDEX_ML_NUMBER_DEFINED_AND         3
//#define INDEX_ML_NUMBER_DEFINED_OR          4
//#define INDEX_ML_NUMBER_DEFINED_XOR         5
//#define INDEX_ML_NUMBER_DEFINED_NOT         6

#define COL_NUMBER_INERATION_BEGIN          6
#define COL_NUMBER_INERATION_END            7

//#define COL_NUMBER_DEFINED_FUNCTIONS_BEGIN  7
//#define COL_NUMBER_DEFINED_FUNCTIONS_END    7
//
//#define COL_NUMBER_DEFINED_TRIGGERS_BEGIN   7
//#define COL_NUMBER_DEFINED_TRIGGERS_END     7
//
//#define COL_NUMBER_DEFINED_AND_BEGIN        7
//#define COL_NUMBER_DEFINED_AND_END          7
//
//#define COL_NUMBER_DEFINED_OR_BEGIN         7
//#define COL_NUMBER_DEFINED_OR_END           7
//
//#define COL_NUMBER_DEFINED_XOR_BEGIN        7
//#define COL_NUMBER_DEFINED_XOR_END          7
//
//#define COL_NUMBER_DEFINED_NOT_BEGIN        6
//#define COL_NUMBER_DEFINED_NOT_END          7

#endif
