#ifndef __CONST_MENU_MTZ__
#define __CONST_MENU_MTZ__

#define EKRAN_SETPOINT_MTZ_GROUP1   (EKRAN_CHOSE_SETTINGS + 1)
#define EKRAN_SETPOINT_MTZ_GROUP2   (EKRAN_SETPOINT_MTZ_GROUP1 + 1)
#define EKRAN_SETPOINT_MTZ_GROUP3   (EKRAN_SETPOINT_MTZ_GROUP2 + 1)
#define EKRAN_SETPOINT_MTZ_GROUP4   (EKRAN_SETPOINT_MTZ_GROUP3 + 1)
#define EKRAN_TIMEOUT_MTZ_GROUP1    (EKRAN_SETPOINT_UP_GROUP4 + 1)
#define EKRAN_TIMEOUT_MTZ_GROUP2    (EKRAN_TIMEOUT_MTZ_GROUP1  + 1)
#define EKRAN_TIMEOUT_MTZ_GROUP3    (EKRAN_TIMEOUT_MTZ_GROUP2  + 1)
#define EKRAN_TIMEOUT_MTZ_GROUP4    (EKRAN_TIMEOUT_MTZ_GROUP3  + 1)
#define EKRAN_CONTROL_MTZ           (EKRAN_TIMEOUT_UP_GROUP4 + 1)

enum _index_ml_stp_msz
{
  INDEX_ML_STPMTZ1 = 0,
  INDEX_ML_STPMTZ1_N_VPERED,
  INDEX_ML_STPMTZ1_N_NAZAD,
  INDEX_ML_STPMTZ1_ANGLE,
  INDEX_ML_STPMTZ1_PO_NAPRUZI,
  INDEX_ML_STPMTZ1_U,
    INDEX_ML_STPMTZ1_K,
  
  INDEX_ML_STPMTZ2,
  INDEX_ML_STPMTZ2_N_VPERED,
  INDEX_ML_STPMTZ2_N_NAZAD,
  INDEX_ML_STPMTZ2_ANGLE,
  INDEX_ML_STPMTZ2_PO_NAPRUZI,
  INDEX_ML_STPMTZ2_U,
    INDEX_ML_STPMTZ2_K,
  
  INDEX_ML_STPMTZ3,
  INDEX_ML_STPMTZ3_N_VPERED,
  INDEX_ML_STPMTZ3_N_NAZAD,
  INDEX_ML_STPMTZ3_ANGLE,
  INDEX_ML_STPMTZ3_PO_NAPRUZI,
  INDEX_ML_STPMTZ3_U,
    INDEX_ML_STPMTZ3_K,
  
  INDEX_ML_STPMTZ4,
  INDEX_ML_STPMTZ4_N_VPERED,
  INDEX_ML_STPMTZ4_N_NAZAD,
  INDEX_ML_STPMTZ4_ANGLE,
  INDEX_ML_STPMTZ4_PO_NAPRUZI,
  INDEX_ML_STPMTZ4_U,
    INDEX_ML_STPMTZ4_K,
  
  MAX_ROW_FOR_SETPOINT_MTZ
};

#define COL_SETPOINT_MTZ_1_BEGIN                3
#define COL_SETPOINT_MTZ_1_COMMA                6
#define COL_SETPOINT_MTZ_1_END                  8

#define COL_SETPOINT_MTZ_1_N_VPERED_BEGIN       3
#define COL_SETPOINT_MTZ_1_N_VPERED_COMMA       6
#define COL_SETPOINT_MTZ_1_N_VPERED_END         8

#define COL_SETPOINT_MTZ_1_N_NAZAD_BEGIN        3
#define COL_SETPOINT_MTZ_1_N_NAZAD_COMMA        6
#define COL_SETPOINT_MTZ_1_N_NAZAD_END          8

#define COL_SETPOINT_MTZ_1_ANGLE_BEGIN          6
#define COL_SETPOINT_MTZ_1_ANGLE_END            7

#define COL_SETPOINT_MTZ_1_PO_NAPRUZI_BEGIN     3
#define COL_SETPOINT_MTZ_1_PO_NAPRUZI_COMMA     6
#define COL_SETPOINT_MTZ_1_PO_NAPRUZI_END       8

#define COL_SETPOINT_MTZ_1_U_BEGIN              3
#define COL_SETPOINT_MTZ_1_U_COMMA              6
#define COL_SETPOINT_MTZ_1_U_END                8

#define COL_SETPOINT_MTZ_1_K_BEGIN              5
#define COL_SETPOINT_MTZ_1_K_COMMA              8
#define COL_SETPOINT_MTZ_1_K_END                10

#define COL_SETPOINT_MTZ_2_BEGIN                3
#define COL_SETPOINT_MTZ_2_COMMA                6
#define COL_SETPOINT_MTZ_2_END                  8

#define COL_SETPOINT_MTZ_2_N_VPERED_BEGIN       3
#define COL_SETPOINT_MTZ_2_N_VPERED_COMMA       6
#define COL_SETPOINT_MTZ_2_N_VPERED_END         8

#define COL_SETPOINT_MTZ_2_N_NAZAD_BEGIN        3
#define COL_SETPOINT_MTZ_2_N_NAZAD_COMMA        6
#define COL_SETPOINT_MTZ_2_N_NAZAD_END          8

#define COL_SETPOINT_MTZ_2_ANGLE_BEGIN          6
#define COL_SETPOINT_MTZ_2_ANGLE_END            7

#define COL_SETPOINT_MTZ_2_PO_NAPRUZI_BEGIN     3
#define COL_SETPOINT_MTZ_2_PO_NAPRUZI_COMMA     6
#define COL_SETPOINT_MTZ_2_PO_NAPRUZI_END       8

#define COL_SETPOINT_MTZ_2_U_BEGIN              3
#define COL_SETPOINT_MTZ_2_U_COMMA              6
#define COL_SETPOINT_MTZ_2_U_END                8

#define COL_SETPOINT_MTZ_2_K_BEGIN              5
#define COL_SETPOINT_MTZ_2_K_COMMA              8
#define COL_SETPOINT_MTZ_2_K_END                10

#define COL_SETPOINT_MTZ_3_BEGIN                3
#define COL_SETPOINT_MTZ_3_COMMA                6
#define COL_SETPOINT_MTZ_3_END                  8

#define COL_SETPOINT_MTZ_3_N_VPERED_BEGIN       3
#define COL_SETPOINT_MTZ_3_N_VPERED_COMMA       6
#define COL_SETPOINT_MTZ_3_N_VPERED_END         8

#define COL_SETPOINT_MTZ_3_N_NAZAD_BEGIN        3
#define COL_SETPOINT_MTZ_3_N_NAZAD_COMMA        6
#define COL_SETPOINT_MTZ_3_N_NAZAD_END          8

#define COL_SETPOINT_MTZ_3_ANGLE_BEGIN          6
#define COL_SETPOINT_MTZ_3_ANGLE_END            7

#define COL_SETPOINT_MTZ_3_PO_NAPRUZI_BEGIN     3
#define COL_SETPOINT_MTZ_3_PO_NAPRUZI_COMMA     6
#define COL_SETPOINT_MTZ_3_PO_NAPRUZI_END       8

#define COL_SETPOINT_MTZ_3_U_BEGIN              3
#define COL_SETPOINT_MTZ_3_U_COMMA              6
#define COL_SETPOINT_MTZ_3_U_END                8

#define COL_SETPOINT_MTZ_3_K_BEGIN              5
#define COL_SETPOINT_MTZ_3_K_COMMA              8
#define COL_SETPOINT_MTZ_3_K_END                10

#define COL_SETPOINT_MTZ_4_BEGIN                3
#define COL_SETPOINT_MTZ_4_COMMA                6
#define COL_SETPOINT_MTZ_4_END                  8

#define COL_SETPOINT_MTZ_4_N_VPERED_BEGIN       3
#define COL_SETPOINT_MTZ_4_N_VPERED_COMMA       6
#define COL_SETPOINT_MTZ_4_N_VPERED_END         8

#define COL_SETPOINT_MTZ_4_N_NAZAD_BEGIN        3
#define COL_SETPOINT_MTZ_4_N_NAZAD_COMMA        6
#define COL_SETPOINT_MTZ_4_N_NAZAD_END          8

#define COL_SETPOINT_MTZ_4_ANGLE_BEGIN          6
#define COL_SETPOINT_MTZ_4_ANGLE_END            7

#define COL_SETPOINT_MTZ_4_PO_NAPRUZI_BEGIN     3
#define COL_SETPOINT_MTZ_4_PO_NAPRUZI_COMMA     6
#define COL_SETPOINT_MTZ_4_PO_NAPRUZI_END       8

#define COL_SETPOINT_MTZ_4_U_BEGIN              3
#define COL_SETPOINT_MTZ_4_U_COMMA              6
#define COL_SETPOINT_MTZ_4_U_END                8

#define COL_SETPOINT_MTZ_4_K_BEGIN              5
#define COL_SETPOINT_MTZ_4_K_COMMA              8
#define COL_SETPOINT_MTZ_4_K_END                10

enum _index_ml_tmo_msz
{
  INDEX_ML_TMOMTZ1 = 0,
  INDEX_ML_TMOMTZ1_N_VPERED,
  INDEX_ML_TMOMTZ1_N_NAZAD,
  INDEX_ML_TMOMTZ1_PO_NAPRUZI,
    INDEX_ML_TMOMTZ1_K,
  
  INDEX_ML_TMOMTZ2,
  INDEX_ML_TMOMTZ2_PR,
  INDEX_ML_TMOMTZ2_N_VPERED,
  INDEX_ML_TMOMTZ2_N_VPERED_PR,
  INDEX_ML_TMOMTZ2_N_NAZAD,
  INDEX_ML_TMOMTZ2_N_NAZAD_PR,
  INDEX_ML_TMOMTZ2_PO_NAPRUZI,
  INDEX_ML_TMOMTZ2_PO_NAPRUZI_PR,
  INDEX_ML_TMOMTZ2_VVID_PR,
    INDEX_ML_TMOMTZ2_K,
  
  INDEX_ML_TMOMTZ3,
  INDEX_ML_TMOMTZ3_N_VPERED,
  INDEX_ML_TMOMTZ3_N_NAZAD,
  INDEX_ML_TMOMTZ3_PO_NAPRUZI,
    INDEX_ML_TMOMTZ3_K,
  
  INDEX_ML_TMOMTZ4,
  INDEX_ML_TMOMTZ4_N_VPERED,
  INDEX_ML_TMOMTZ4_N_NAZAD,
  INDEX_ML_TMOMTZ4_PO_NAPRUZI,
    INDEX_ML_TMOMTZ4_K,
  
  MAX_ROW_FOR_TIMEOUT_MTZ
};

#define COL_TMO_MTZ_1_BEGIN                     4
#define COL_TMO_MTZ_1_COMMA                     6
#define COL_TMO_MTZ_1_END                       8

#define COL_TMO_MTZ_1_N_VPERED_BEGIN            4
#define COL_TMO_MTZ_1_N_VPERED_COMMA            6
#define COL_TMO_MTZ_1_N_VPERED_END              8

#define COL_TMO_MTZ_1_N_NAZAD_BEGIN             4
#define COL_TMO_MTZ_1_N_NAZAD_COMMA             6
#define COL_TMO_MTZ_1_N_NAZAD_END               8

#define COL_TMO_MTZ_1_PO_NAPRUZI_BEGIN          4
#define COL_TMO_MTZ_1_PO_NAPRUZI_COMMA          6
#define COL_TMO_MTZ_1_PO_NAPRUZI_END            8

#define COL_TMO_MTZ_1_K_BEGIN          5
#define COL_TMO_MTZ_1_K_COMMA          8
#define COL_TMO_MTZ_1_K_END            10

#define COL_TMO_MTZ_2_BEGIN                     3
#define COL_TMO_MTZ_2_COMMA                     6
#define COL_TMO_MTZ_2_END                       8

#define COL_TMO_MTZ_2_PR_BEGIN                  5
#define COL_TMO_MTZ_2_PR_COMMA                  6
#define COL_TMO_MTZ_2_PR_END                    8

#define COL_TMO_MTZ_2_N_VPERED_BEGIN            3
#define COL_TMO_MTZ_2_N_VPERED_COMMA            6
#define COL_TMO_MTZ_2_N_VPERED_END              8

#define COL_TMO_MTZ_2_N_VPERED_PR_BEGIN         5
#define COL_TMO_MTZ_2_N_VPERED_PR_COMMA         6
#define COL_TMO_MTZ_2_N_VPERED_PR_END           8

#define COL_TMO_MTZ_2_N_NAZAD_BEGIN             3
#define COL_TMO_MTZ_2_N_NAZAD_COMMA             6
#define COL_TMO_MTZ_2_N_NAZAD_END               8

#define COL_TMO_MTZ_2_N_NAZAD_PR_BEGIN          5
#define COL_TMO_MTZ_2_N_NAZAD_PR_COMMA          6
#define COL_TMO_MTZ_2_N_NAZAD_PR_END            8

#define COL_TMO_MTZ_2_PO_NAPRUZI_BEGIN          3
#define COL_TMO_MTZ_2_PO_NAPRUZI_COMMA          6
#define COL_TMO_MTZ_2_PO_NAPRUZI_END            8

#define COL_TMO_MTZ_2_PO_NAPRUZI_PR_BEGIN       5
#define COL_TMO_MTZ_2_PO_NAPRUZI_PR_COMMA       6
#define COL_TMO_MTZ_2_PO_NAPRUZI_PR_END         8

#define COL_TMO_MTZ_2_VVID_PR_BEGIN             5
#define COL_TMO_MTZ_2_VVID_PR_COMMA             6
#define COL_TMO_MTZ_2_VVID_PR_END               8

#define COL_TMO_MTZ_2_K_BEGIN          5
#define COL_TMO_MTZ_2_K_COMMA          8
#define COL_TMO_MTZ_2_K_END            10

#define COL_TMO_MTZ_3_BEGIN                     3
#define COL_TMO_MTZ_3_COMMA                     6
#define COL_TMO_MTZ_3_END                       8

#define COL_TMO_MTZ_3_N_VPERED_BEGIN            3
#define COL_TMO_MTZ_3_N_VPERED_COMMA            6
#define COL_TMO_MTZ_3_N_VPERED_END              8

#define COL_TMO_MTZ_3_N_NAZAD_BEGIN             3
#define COL_TMO_MTZ_3_N_NAZAD_COMMA             6
#define COL_TMO_MTZ_3_N_NAZAD_END               8

#define COL_TMO_MTZ_3_PO_NAPRUZI_BEGIN          3
#define COL_TMO_MTZ_3_PO_NAPRUZI_COMMA          6
#define COL_TMO_MTZ_3_PO_NAPRUZI_END            8

#define COL_TMO_MTZ_3_K_BEGIN          5
#define COL_TMO_MTZ_3_K_COMMA          8
#define COL_TMO_MTZ_3_K_END            10

#define COL_TMO_MTZ_4_BEGIN                     3
#define COL_TMO_MTZ_4_COMMA                     6
#define COL_TMO_MTZ_4_END                       8

#define COL_TMO_MTZ_4_N_VPERED_BEGIN            3
#define COL_TMO_MTZ_4_N_VPERED_COMMA            6
#define COL_TMO_MTZ_4_N_VPERED_END              8

#define COL_TMO_MTZ_4_N_NAZAD_BEGIN             3
#define COL_TMO_MTZ_4_N_NAZAD_COMMA             6
#define COL_TMO_MTZ_4_N_NAZAD_END               8

#define COL_TMO_MTZ_4_PO_NAPRUZI_BEGIN          3
#define COL_TMO_MTZ_4_PO_NAPRUZI_COMMA          6
#define COL_TMO_MTZ_4_PO_NAPRUZI_END            8

#define COL_TMO_MTZ_4_K_BEGIN          5
#define COL_TMO_MTZ_4_K_COMMA          8
#define COL_TMO_MTZ_4_K_END            10

enum _n_bit_ctrl_msz
{
  N_BIT_CTRMTZ_1 = 0,
  N_BIT_CTRMTZ_1_VPERED,
  N_BIT_CTRMTZ_1_NAZAD,
  N_BIT_CTRMTZ_1_ZNAM,
  N_BIT_CTRMTZ_1_ZNAM_TYPE,

  N_BIT_CTRMTZ_2,
  N_BIT_CTRMTZ_2_VPERED,
  N_BIT_CTRMTZ_2_NAZAD,
  N_BIT_CTRMTZ_2_PRYSKORENNJA,
  N_BIT_CTRMTZ_2_PRYSKORENA,
  N_BIT_CTRMTZ_2_ZNAM,
  N_BIT_CTRMTZ_2_ZNAM_TYPE,

  N_BIT_CTRMTZ_3,
  N_BIT_CTRMTZ_3_VPERED,
  N_BIT_CTRMTZ_3_NAZAD,
  N_BIT_CTRMTZ_3_ZNAM,
  N_BIT_CTRMTZ_3_ZNAM_TYPE,

  N_BIT_CTRMTZ_4,
  N_BIT_CTRMTZ_4_VPERED,
  N_BIT_CTRMTZ_4_NAZAD,
  N_BIT_CTRMTZ_4_ZNAM,
  N_BIT_CTRMTZ_4_ZNAM_TYPE,

  N_BIT_CTRMTZ_NESPR_KIL_NAPR,
  
  NUMBER_BITS_CTRMTZ
		
};
#define CTR_MTZ_MASKA  (MASKA_FOR_BIT(NUMBER_BITS_CTRMTZ) - 1)

enum _index_ml_ctrl_msz
{
  INDEX_ML_CTRMTZ_1 = 0,
  INDEX_ML_CTRMTZ_1_TYPE,
  INDEX_ML_CTRMTZ_1_VPERED,
  INDEX_ML_CTRMTZ_1_NAZAD,
    INDEX_ML_CTRMTZ_1_ZNAM,
    INDEX_ML_CTRMTZ_1_ZNAM_TYPE,
  
  INDEX_ML_CTRMTZ_2,
  INDEX_ML_CTRMTZ_2_TYPE,
  INDEX_ML_CTRMTZ_2_VPERED,
  INDEX_ML_CTRMTZ_2_NAZAD,
  INDEX_ML_CTRMTZ_2_PRYSKORENNJA,
  INDEX_ML_CTRMTZ_2_PRYSKORENA,
    INDEX_ML_CTRMTZ_2_ZNAM,
    INDEX_ML_CTRMTZ_2_ZNAM_TYPE,
  
  INDEX_ML_CTRMTZ_3,
  INDEX_ML_CTRMTZ_3_TYPE,
  INDEX_ML_CTRMTZ_3_VPERED,
  INDEX_ML_CTRMTZ_3_NAZAD,
    INDEX_ML_CTRMTZ_3_ZNAM,
    INDEX_ML_CTRMTZ_3_ZNAM_TYPE,
  
  INDEX_ML_CTRMTZ_4,
  INDEX_ML_CTRMTZ_4_TYPE,
  INDEX_ML_CTRMTZ_4_VPERED,
  INDEX_ML_CTRMTZ_4_NAZAD,
    INDEX_ML_CTRMTZ_4_ZNAM,
    INDEX_ML_CTRMTZ_4_ZNAM_TYPE,
  
  INDEX_ML_CTRMTZ_NESPR_KIL_NAPR,
  
  MAX_ROW_FOR_CONTROL_MTZ
};

enum 
{
  CTR_MTZ = 0,
  CTR_MTZ_VPERED,
  CTR_MTZ_NAZAD,
	CTR_MTZ_PRYSKORENNJA,
	CTR_MTZ_PRYSKORENA,
	CTR_MTZ_ZNAM,
	CTR_MTZ_ZNAM_TYPE,
  /*************************************/
  MTZ_CONST_MENU_SETTINGS_LENGTH
};

enum __mtz_tmr_const 
{
  INDEX_TIMER_MTZ = 0,
  INDEX_TIMER_MTZ_N_VPERED,
  INDEX_TIMER_MTZ_N_NAZAD,
  INDEX_TIMER_MTZ_PO_NAPRUZI,
	
  INDEX_TIMER_MTZ_DEPENDENT_A,
  INDEX_TIMER_MTZ_DEPENDENT_B,
  INDEX_TIMER_MTZ_DEPENDENT_C,
  INDEX_TIMER_MTZ_DEPENDENT_RT_80,
  INDEX_TIMER_MTZ_DEPENDENT_RTV_I,
	
	INDEX_TIMER_MTZ_PR,
	INDEX_TIMER_MTZ_N_VPERED_PR,
	INDEX_TIMER_MTZ_N_NAZAD_PR,
	INDEX_TIMER_MTZ_PO_NAPRUZI_PR,
	INDEX_TIMER_MTZ_VVID_PR,
	
  /*************************************/
  NUMBER_LEVEL_OCP_TMR_CONST
};


enum __mtz_const 
{
  RANG_BLOCK_MTZ = 0,
  RANG_BLOCK_USK_MTZ,
  RANG_SECTOR_VPERED_MTZN,
  RANG_SECTOR_NAZAD_MTZN,
  RANG_PO_MTZ,
  RANG_PO_MTZN_VPERED,
  RANG_PO_MTZN_NAZAD,
  RANG_PO_U_MTZPN,
  RANG_PO_MTZPN,
  RANG_MTZ,
  /*************************************/
  OCP_SIGNALS_LENGTH
};

enum __mtz_levels_const 
{
  OCP_LEVEL1 = 0,
  OCP_LEVEL2,
  OCP_LEVEL3,
  OCP_LEVEL4,
  /*************************************/
  NUMBER_LEVEL_OCP
};

enum __mtz_abc_direction_const {
  MTZ_NEVYZN = 0,
  MTZ_VPERED,
  MTZ_NAZAD
};

enum __mtz_abc_const {
  PHASE_A_INDEX = 0,
  PHASE_B_INDEX,
  PHASE_C_INDEX
};

#endif
