#ifndef __CONST_MENU_ZNAM__
#define __CONST_MENU_ZNAM__

#define EKRAN_SETPOINT_ZNAM_GROUP1 (EKRAN_SETPOINT_DZ_GROUP4 + 1)
#define EKRAN_SETPOINT_ZNAM_GROUP2 (EKRAN_SETPOINT_ZNAM_GROUP1 + 1)
#define EKRAN_SETPOINT_ZNAM_GROUP3 (EKRAN_SETPOINT_ZNAM_GROUP2 + 1)
#define EKRAN_SETPOINT_ZNAM_GROUP4 (EKRAN_SETPOINT_ZNAM_GROUP3 + 1)
#define EKRAN_TIMEOUT_ZNAM_GROUP1  (EKRAN_TIMEOUT_DZ_GROUP4  + 1)
#define EKRAN_TIMEOUT_ZNAM_GROUP2  (EKRAN_TIMEOUT_ZNAM_GROUP1  + 1)
#define EKRAN_TIMEOUT_ZNAM_GROUP3  (EKRAN_TIMEOUT_ZNAM_GROUP2  + 1)
#define EKRAN_TIMEOUT_ZNAM_GROUP4  (EKRAN_TIMEOUT_ZNAM_GROUP3  + 1)
#define EKRAN_CONTROL_ZNAM         (EKRAN_CONTROL_DZ + 1)

enum _index_ml_stp_znam
{
  INDEX_ML_STP_ZNAM = 0,
  
  MAX_ROW_FOR_SETPOINT_ZNAM
};

#define COL_SETPOINT_ZNAM_BEGIN    3
#define COL_SETPOINT_ZNAM_COMMA    4
#define COL_SETPOINT_ZNAM_END      7

enum _index_ml_tmo_znam
{
  INDEX_ML_TMO_ZNAM = 0,
  
  MAX_ROW_FOR_TIMEOUT_ZNAM
};

#define COL_TMO_ZNAM_BEGIN         5
#define COL_TMO_ZNAM_COMMA         6
#define COL_TMO_ZNAM_END           8

enum _index_ml_ctrl_znam
{
  CTR_ZNAM_STATE_BIT = 0,
  
  _CTR_ZNAM_NEXT_BIT,
  MAX_ROW_FOR_CONTROL_ZNAM = _CTR_ZNAM_NEXT_BIT
};


#define CTR_ZNAM_MASKA             (MASKA_FOR_BIT(_CTR_ZNAM_NEXT_BIT) - 1)

#endif
