#ifndef __CONSTANTS_DEFINED_AND__
#define __CONSTANTS_DEFINED_AND__

#define EKRAN_LIST_D_AND                    (EKRAN_RANGUVANNJA_RESET_DT4_MINUS + 1)
#define EKRAN_RANGUVANNJA_D_AND1            (EKRAN_LIST_D_AND + 1)
#define EKRAN_RANGUVANNJA_D_AND2            (EKRAN_RANGUVANNJA_D_AND1 + 1)
#define EKRAN_RANGUVANNJA_D_AND3            (EKRAN_RANGUVANNJA_D_AND2 + 1)
#define EKRAN_RANGUVANNJA_D_AND4            (EKRAN_RANGUVANNJA_D_AND3 + 1)
#define EKRAN_RANGUVANNJA_D_AND5            (EKRAN_RANGUVANNJA_D_AND4 + 1)
#define EKRAN_RANGUVANNJA_D_AND6            (EKRAN_RANGUVANNJA_D_AND5 + 1)
#define EKRAN_RANGUVANNJA_D_AND7            (EKRAN_RANGUVANNJA_D_AND6 + 1)
#define EKRAN_RANGUVANNJA_D_AND8            (EKRAN_RANGUVANNJA_D_AND7 + 1)

#define MAX_ROW_FOR_LIST_D_AND              NUMBER_DEFINED_AND/*((int)current_settings.number_defined_and)*/
#define MAX_ROW_RANGUVANNJA_D_AND           NUMBER_TOTAL_SIGNAL_FOR_RANG

#endif 
