#ifndef __CONST_MENU_EXTENDED_LIGIC__
#define __CONST_MENU_EXTENDED_LIGIC__

#define EKRAN_EXTENDED_LIGIC        (EKRAN_CONTROL_AR + 1)

enum _index_ml_ctrl_EXTENDED_LIGIC
{
  INDEX_OF_GENERAL_PICKUP_EL = 0,
  INDEX_OF_DEFINED_FUNCTIONS,
  INDEX_OF_DEFINED_TRIGGERS,
  INDEX_OF_DEFINED_AND,
  INDEX_OF_DEFINED_OR,
  INDEX_OF_DEFINED_XOR,
  INDEX_OF_DEFINED_NOT,
  INDEX_OF_TRANSFER_FUNCTIONS,
  
  MAX_ROW_FOR_EXTENDED_LIGIC
};

#endif
